name: call-me
description: "Call me, anytime"

inputs:
  actor:
    required: true
  token: 
    required: true

runs:
  using: composite
  steps:
    -
      name: What-Envs
      shell: bash
      run: |
        echo "Passed in: ${PASSED_IN}"
        export NEW_VAR="this+${PASSED_IN}"
    - 
      name: New-Envs
      shell: bash
      run: |
        echo "Passed in ${PASSED_IN}"
        echo "${NEW_VAR}"
        
