name: Main-Job

env:
  PASSED_IN: this
  NEW_VAR: ""

on:
  push:
    branches:
      - main

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: My-Envs
        run: |
          echo "In Main: ${PASSED_IN}"
      -
        name: Action-Envs
        uses: ./.github/actions/call-me
        with:
          actor: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}



