name: Create and Publish Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'toolnotes/*'

env:
  REGISTRY: ghcr.io
  # IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set Image Tag
        run: echo IMAGE_TAG=$(cat toolnotes/VERSION.txt) >> ${GITHUB_ENV}
      -
        name: Is this a new VERSION
        run: |
          PULL_TOKEN=$(curl -Ls -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://ghcr.io/token\?scope\="repository:cmaahs/toolnotes:pull" | jq -r '.token')
          echo $PULL_TOKEN
          TAG_EXISTS=$(curl -Ls -H "Authorization: Bearer ${PULL_TOKEN}" https://ghcr.io/v2/cmaahs/toolnotes/tags/list | jq -r '.tags[] | select(.=="${{ env.IMAGE_TAG }}")')
          if [[ -n ${TAG_EXISTS} ]]; then
            echo "This version already exists, please update VERSION.txt and CHANGELOG.md"
            exit 1
          fi
      # -
      #   name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./toolnotes/
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/cmaahs/toolnotes:${{ env.IMAGE_TAG }}
